// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATV_OlJFgdOovXS3AipFXrVKJq1gZMA-E',
    appId: '1:111159286966:web:852807c4b471ed5dbd1a17',
    messagingSenderId: '111159286966',
    projectId: 'picfeed-app',
    authDomain: 'picfeed-app.firebaseapp.com',
    storageBucket: 'picfeed-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bMlaHlWMrZ6TpwICbUfxn1fJ5Q0b_g4',
    appId: '1:111159286966:android:347e2cc31fc29965bd1a17',
    messagingSenderId: '111159286966',
    projectId: 'picfeed-app',
    storageBucket: 'picfeed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtalxUNlY1wnyNX3SH5TuLU17rrE0RBLc',
    appId: '1:111159286966:ios:ff6aadeaff4e1865bd1a17',
    messagingSenderId: '111159286966',
    projectId: 'picfeed-app',
    storageBucket: 'picfeed-app.appspot.com',
    iosClientId: '111159286966-5kfk9jg0pcqanm0seocr70bd14p031vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.picfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtalxUNlY1wnyNX3SH5TuLU17rrE0RBLc',
    appId: '1:111159286966:ios:ff6aadeaff4e1865bd1a17',
    messagingSenderId: '111159286966',
    projectId: 'picfeed-app',
    storageBucket: 'picfeed-app.appspot.com',
    iosClientId: '111159286966-5kfk9jg0pcqanm0seocr70bd14p031vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.picfeed',
  );
}
